name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Compilar el proyecto principal
      - name: Restore dependencies
        run: dotnet restore ./specs/src/BibliotecaSD.csproj

      - name: Build
        run: dotnet build ./specs/src/BibliotecaSD.csproj --no-restore

      # Ejecutar pruebas unitarias
      - name: Test
        run: dotnet test ./specs/tests/BibliotecaSD.Tests.csproj --no-build --verbosity normal